version: '3.8'

services:    
    postgres:
        image: postgres:13
        hostname: postgree_hostname
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=test
            - POSTGRES_DB=test
        ports:
            - 6666:5432
        volumes:
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        tmpfs:
            - /var/lib/postgresql/data
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5